language: node_js
node_js:
  - node
before_install:
  - wget $ASSET_ZIP -O file.zip
  - unzip -o file.zip
script: yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  local_dir: build
  skip_cleanup: true